/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[AddressType]
(
[column1] [tinyint] NOT NULL,
[column2] [nvarchar] (50) NOT NULL,
[column3] [nvarchar] (50) NOT NULL,
[column4] [datetime2] NOT NULL
)
GO
