/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Address]
(
[column1] [smallint] NOT NULL,
[column2] [nvarchar] (50) NOT NULL,
[column3] [nvarchar] (50) NULL,
[column4] [nvarchar] (50) NOT NULL,
[column5] [tinyint] NOT NULL,
[column6] [nvarchar] (50) NOT NULL,
[column7] [nvarchar] (50) NOT NULL,
[column8] [nvarchar] (50) NOT NULL,
[column9] [nvarchar] (50) NOT NULL
)
GO
